RNetCDF release 1.1-1
git-svn-id: svn://r-forge.r-project.org/svnroot/rnetcdf@4 edb9625f-4e0d-4859-8d74-9fd3b1da38cb

diff --git a/pkg/configure b/pkg/configure
--- a/pkg/configure
+++ b/pkg/configure
@@ -1729,14 +1729,15 @@ echo "$as_me: error: udunits library not found" >&2;}
     exit 1
 fi
 
+HAVE_NETCDF_H=FALSE
 if test -z "${NETCDF_PATH}"; then
-    echo "$as_me:1733: checking for /usr/local/include/netcdf.h" >&5
+    echo "$as_me:1734: checking for /usr/local/include/netcdf.h" >&5
 echo $ECHO_N "checking for /usr/local/include/netcdf.h... $ECHO_C" >&6
 if test "${ac_cv_file__usr_local_include_netcdf_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   test "$cross_compiling" = yes &&
-  { { echo "$as_me:1739: error: cannot check for file existence when cross compiling" >&5
+  { { echo "$as_me:1740: error: cannot check for file existence when cross compiling" >&5
 echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
    { (exit 1); exit 1; }; }
 if test -r "/usr/local/include/netcdf.h"; then
@@ -1745,26 +1746,27 @@ else
   ac_cv_file__usr_local_include_netcdf_h=no
 fi
 fi
-echo "$as_me:1748: result: $ac_cv_file__usr_local_include_netcdf_h" >&5
+echo "$as_me:1749: result: $ac_cv_file__usr_local_include_netcdf_h" >&5
 echo "${ECHO_T}$ac_cv_file__usr_local_include_netcdf_h" >&6
 if test $ac_cv_file__usr_local_include_netcdf_h = yes; then
-  USR_LOCAL_NETCDF=TRUE
+  USR_LOCAL_NETCDF_H=TRUE
 else
-  USR_LOCAL_NETCDF=FALSE
+  USR_LOCAL_NETCDF_H=FALSE
 fi
 
-        if test "${USR_LOCAL_NETCDF}" = TRUE; then
-	    NETCDF_INCDIR="/usr/local/include"
-	    NETCDF_LIBDIR="/usr/local/lib"
-	    NETCDF_LIBNAME="netcdf"
-        fi
-    echo "$as_me:1761: checking for /usr/include/netcdf.h" >&5
+    if test "${USR_LOCAL_NETCDF_H}" = TRUE; then
+	NETCDF_INCDIR="/usr/local/include"
+	NETCDF_LIBDIR="/usr/local/lib"
+	NETCDF_LIBNAME="netcdf"
+	HAVE_NETCDF_H=TRUE
+    elif test "${HAVE_NETCDF_H}" = FALSE; then
+        echo "$as_me:1763: checking for /usr/include/netcdf.h" >&5
 echo $ECHO_N "checking for /usr/include/netcdf.h... $ECHO_C" >&6
 if test "${ac_cv_file__usr_include_netcdf_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   test "$cross_compiling" = yes &&
-  { { echo "$as_me:1767: error: cannot check for file existence when cross compiling" >&5
+  { { echo "$as_me:1769: error: cannot check for file existence when cross compiling" >&5
 echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
    { (exit 1); exit 1; }; }
 if test -r "/usr/include/netcdf.h"; then
@@ -1773,96 +1775,33 @@ else
   ac_cv_file__usr_include_netcdf_h=no
 fi
 fi
-echo "$as_me:1776: result: $ac_cv_file__usr_include_netcdf_h" >&5
+echo "$as_me:1778: result: $ac_cv_file__usr_include_netcdf_h" >&5
 echo "${ECHO_T}$ac_cv_file__usr_include_netcdf_h" >&6
 if test $ac_cv_file__usr_include_netcdf_h = yes; then
-  USR_NETCDF=TRUE
+  USR_NETCDF_H=TRUE
 else
-  USR_NETCDF=FALSE
+  USR_NETCDF_H=FALSE
 fi
 
-        if test "${USR_NETCDF}" = TRUE; then
+        if test "${USR_NETCDF_H}" = TRUE; then
 	    NETCDF_INCDIR="/usr/include"
 	    NETCDF_LIBDIR="/usr/lib"
 	    NETCDF_LIBNAME="netcdf"
-        fi
+	    HAVE_NETCDF_H=TRUE
+	fi
+    fi
 else
     NETCDF_INCDIR="${NETCDF_PATH}/include"
     NETCDF_LIBDIR="${NETCDF_PATH}/lib"
     NETCDF_LIBNAME="netcdf"
-fi
-
-if test -z "${UDUNITS_PATH}"; then
-    echo "$as_me:1796: checking for /usr/local/include/udunits.h" >&5
-echo $ECHO_N "checking for /usr/local/include/udunits.h... $ECHO_C" >&6
-if test "${ac_cv_file__usr_local_include_udunits_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:1802: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "/usr/local/include/udunits.h"; then
-  ac_cv_file__usr_local_include_udunits_h=yes
-else
-  ac_cv_file__usr_local_include_udunits_h=no
-fi
-fi
-echo "$as_me:1811: result: $ac_cv_file__usr_local_include_udunits_h" >&5
-echo "${ECHO_T}$ac_cv_file__usr_local_include_udunits_h" >&6
-if test $ac_cv_file__usr_local_include_udunits_h = yes; then
-  USR_LOCAL_UDUNITS=TRUE
-else
-  USR_LOCAL_UDUNITS=FALSE
-fi
-
-        if test "${USR_LOCAL_UDUNITS}" = TRUE; then
-	    UDUNITS_INCDIR="/usr/local/include"
-	    UDUNITS_LIBDIR="/usr/local/lib"
-	    UDUNITS_LIBNAME="udunits"
-        fi
-    echo "$as_me:1824: checking for /usr/include/udunits.h" >&5
-echo $ECHO_N "checking for /usr/include/udunits.h... $ECHO_C" >&6
-if test "${ac_cv_file__usr_include_udunits_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  test "$cross_compiling" = yes &&
-  { { echo "$as_me:1830: error: cannot check for file existence when cross compiling" >&5
-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-   { (exit 1); exit 1; }; }
-if test -r "/usr/include/udunits.h"; then
-  ac_cv_file__usr_include_udunits_h=yes
-else
-  ac_cv_file__usr_include_udunits_h=no
-fi
-fi
-echo "$as_me:1839: result: $ac_cv_file__usr_include_udunits_h" >&5
-echo "${ECHO_T}$ac_cv_file__usr_include_udunits_h" >&6
-if test $ac_cv_file__usr_include_udunits_h = yes; then
-  USR_UDUNITS=TRUE
-else
-  USR_UDUNITS=FALSE
-fi
-
-        if test "${USR_UDUNITS}" = TRUE; then
-	    UDUNITS_INCDIR="/usr/include"
-	    UDUNITS_LIBDIR="/usr/lib"
-	    UDUNITS_LIBNAME="udunits"
-        fi
-else
-    UDUNITS_INCDIR="${UDUNITS_PATH}/include"
-    UDUNITS_LIBDIR="${UDUNITS_PATH}/lib"
-    UDUNITS_LIBNAME="udunits"
-fi
-
-as_ac_File=`echo "ac_cv_file_${NETCDF_INCDIR}/netcdf.h" | $as_tr_sh`
-echo "$as_me:1859: checking for ${NETCDF_INCDIR}/netcdf.h" >&5
+    as_ac_File=`echo "ac_cv_file_${NETCDF_INCDIR}/netcdf.h" | $as_tr_sh`
+echo "$as_me:1798: checking for ${NETCDF_INCDIR}/netcdf.h" >&5
 echo $ECHO_N "checking for ${NETCDF_INCDIR}/netcdf.h... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   test "$cross_compiling" = yes &&
-  { { echo "$as_me:1865: error: cannot check for file existence when cross compiling" >&5
+  { { echo "$as_me:1804: error: cannot check for file existence when cross compiling" >&5
 echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
    { (exit 1); exit 1; }; }
 if test -r "${NETCDF_INCDIR}/netcdf.h"; then
@@ -1871,29 +1810,100 @@ else
   eval "$as_ac_File=no"
 fi
 fi
-echo "$as_me:1874: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "$as_me:1813: result: `eval echo '${'$as_ac_File'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
 if test `eval echo '${'$as_ac_File'}'` = yes; then
-  HAVE_NETCDF_H=TRUE
+  INCDIR_NETCDF_H=TRUE
 else
-  HAVE_NETCDF_H=FALSE
+  INCDIR_NETCDF_H=FALSE
+fi
+
+    if test "${INCDIR_NETCDF_H}" = TRUE; then
+        HAVE_NETCDF_H=TRUE
+    fi
+
 fi
 
 if test "${HAVE_NETCDF_H}" = FALSE; then
-    { { echo "$as_me:1883: error: netcdf.h not found" >&5
+    { { echo "$as_me:1828: error: netcdf.h not found" >&5
 echo "$as_me: error: netcdf.h not found" >&2;}
    { (exit 1); exit 1; }; }
     exit 1
 fi
 
-as_ac_File=`echo "ac_cv_file_${UDUNITS_INCDIR}/udunits.h" | $as_tr_sh`
-echo "$as_me:1890: checking for ${UDUNITS_INCDIR}/udunits.h" >&5
+HAVE_UDUNITS_H=FALSE
+if test -z "${UDUNITS_PATH}"; then
+    echo "$as_me:1836: checking for /usr/local/include/udunits.h" >&5
+echo $ECHO_N "checking for /usr/local/include/udunits.h... $ECHO_C" >&6
+if test "${ac_cv_file__usr_local_include_udunits_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:1842: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/usr/local/include/udunits.h"; then
+  ac_cv_file__usr_local_include_udunits_h=yes
+else
+  ac_cv_file__usr_local_include_udunits_h=no
+fi
+fi
+echo "$as_me:1851: result: $ac_cv_file__usr_local_include_udunits_h" >&5
+echo "${ECHO_T}$ac_cv_file__usr_local_include_udunits_h" >&6
+if test $ac_cv_file__usr_local_include_udunits_h = yes; then
+  USR_LOCAL_UDUNITS_H=TRUE
+else
+  USR_LOCAL_UDUNITS_H=FALSE
+fi
+
+    if test "${USR_LOCAL_UDUNITS_H}" = TRUE; then
+	UDUNITS_INCDIR="/usr/local/include"
+	UDUNITS_LIBDIR="/usr/local/lib"
+	UDUNITS_LIBNAME="udunits"
+	HAVE_UDUNITS_H=TRUE
+    elif test "${HAVE_UDUNITS_H}" = FALSE; then
+        echo "$as_me:1865: checking for /usr/include/udunits.h" >&5
+echo $ECHO_N "checking for /usr/include/udunits.h... $ECHO_C" >&6
+if test "${ac_cv_file__usr_include_udunits_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:1871: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/usr/include/udunits.h"; then
+  ac_cv_file__usr_include_udunits_h=yes
+else
+  ac_cv_file__usr_include_udunits_h=no
+fi
+fi
+echo "$as_me:1880: result: $ac_cv_file__usr_include_udunits_h" >&5
+echo "${ECHO_T}$ac_cv_file__usr_include_udunits_h" >&6
+if test $ac_cv_file__usr_include_udunits_h = yes; then
+  USR_UDUNITS_H=TRUE
+else
+  USR_UDUNITS_H=FALSE
+fi
+
+        if test "${USR_UDUNITS_H}" = TRUE; then
+	    UDUNITS_INCDIR="/usr/include"
+	    UDUNITS_LIBDIR="/usr/lib"
+	    UDUNITS_LIBNAME="udunits"
+	    HAVE_UDUNITS_H=TRUE
+	fi
+    fi
+else
+    UDUNITS_INCDIR="${UDUNITS_PATH}/include"
+    UDUNITS_LIBDIR="${UDUNITS_PATH}/lib"
+    UDUNITS_LIBNAME="udunits"
+    as_ac_File=`echo "ac_cv_file_${UDUNITS_INCDIR}/udunits.h" | $as_tr_sh`
+echo "$as_me:1900: checking for ${UDUNITS_INCDIR}/udunits.h" >&5
 echo $ECHO_N "checking for ${UDUNITS_INCDIR}/udunits.h... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   test "$cross_compiling" = yes &&
-  { { echo "$as_me:1896: error: cannot check for file existence when cross compiling" >&5
+  { { echo "$as_me:1906: error: cannot check for file existence when cross compiling" >&5
 echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
    { (exit 1); exit 1; }; }
 if test -r "${UDUNITS_INCDIR}/udunits.h"; then
@@ -1902,16 +1912,22 @@ else
   eval "$as_ac_File=no"
 fi
 fi
-echo "$as_me:1905: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "$as_me:1915: result: `eval echo '${'$as_ac_File'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
 if test `eval echo '${'$as_ac_File'}'` = yes; then
-  HAVE_UDUNITS_H=TRUE
+  INCDIR_UDUNITS_H=TRUE
 else
-  HAVE_UDUNITS_H=FALSE
+  INCDIR_UDUNITS_H=FALSE
+fi
+
+    if test "${USR_UDUNITS_H}" = TRUE; then
+        HAVE_UDUNITS_H=TRUE
+    fi
+
 fi
 
 if test "${HAVE_UDUNITS_H}" = FALSE; then
-    { { echo "$as_me:1914: error: udunits.h not found" >&5
+    { { echo "$as_me:1930: error: udunits.h not found" >&5
 echo "$as_me: error: udunits.h not found" >&2;}
    { (exit 1); exit 1; }; }
     exit 1
@@ -2027,7 +2043,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:2030: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:2046: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -2194,7 +2210,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:2197: error: ambiguous option: $1
+    { { echo "$as_me:2213: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2213,7 +2229,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:2216: error: unrecognized option: $1
+  -*) { { echo "$as_me:2232: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -2250,7 +2266,7 @@ do
   # Handling of arguments.
   "R/load.R" ) CONFIG_FILES="$CONFIG_FILES R/load.R" ;;
   "src/Makevars" ) CONFIG_FILES="$CONFIG_FILES src/Makevars" ;;
-  *) { { echo "$as_me:2253: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:2269: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2454,7 +2470,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2457: creating $ac_file" >&5
+    { echo "$as_me:2473: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2472,7 +2488,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2475: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2491: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2485,7 +2501,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2488: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2504: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
