More debugging of R package paths

diff --git a/.github/workflows/check-linux-mpi.yaml b/.github/workflows/check-linux-mpi.yaml
--- a/.github/workflows/check-linux-mpi.yaml
+++ b/.github/workflows/check-linux-mpi.yaml
@@ -39,16 +39,16 @@ jobs:
         run: |
             sudo apt-get install -y libnetcdf-mpi-dev libopenmpi-dev openmpi-bin
 
+      - name: Install Rmpi
+        run: |
+          Rscript -e 'install.packages("Rmpi", type="source", configure.args="--with-mpi=/usr/lib/x86_64-linux-gnu/openmpi --with-Rmpi-type=OPENMPI")'
+          Rscript -e 'for (path in .libPaths()) {cat("All packages on ", path, ":\n"); print(list.files(path)); }'
+
       - name: Install R dependencies
         uses: r-lib/actions/setup-r-dependencies@v2
         with:
           extra-packages: any::rcmdcheck, pbdMPI=?ignore, Rmpi=?ignore
           needs: check
-
-      - name: Install Rmpi
-        run: |
-          Rscript -e 'install.packages("Rmpi", type="source", configure.args="--with-mpi=/usr/lib/x86_64-linux-gnu/openmpi --with-Rmpi-type=OPENMPI")'
-          Rscript -e 'for (path in .libPaths()) {cat("All packages on ", path, ":\n"); print(list.files(path)); }'
 
       - name: Check RNetCDF package
         id: rcmdcheck
@@ -56,12 +56,14 @@ jobs:
         with:
           check-dir: '"check"'
           args: 'c("--no-manual", "--as-cran", "--install-args=--configure-args=\"--without-nc-config --with-mpiexec=mpiexec.openmpi CC=mpicc.openmpi CPPFLAGS=-I/usr/lib/x86_64-linux-gnu/netcdf/mpi/include LDFLAGS=-L/usr/lib/x86_64-linux-gnu/netcdf/mpi\"")'
-
-      - name: Upload check directory
-        if: success() || failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: ${{ matrix.config.os }}_r-${{ matrix.config.r }}_mpi_check
-          path: check/
+          upload-results: true
           retention-days: 5
+
+#      - name: Upload check directory
+#        if: success() || failure()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: ${{ matrix.config.os }}_r-${{ matrix.config.r }}_mpi_check
+#          path: check/
+#          retention-days: 5
 
