Filter "too many states" errors from bcheck, not maacheck

diff --git a/.github/workflows/test-rchk.yaml b/.github/workflows/test-rchk.yaml
--- a/.github/workflows/test-rchk.yaml
+++ b/.github/workflows/test-rchk.yaml
@@ -37,22 +37,25 @@ jobs:
         cd /home/docker/R-svn/
         /home/docker/rchk/scripts/check_package.sh $PACKAGE bcheck maacheck fficheck
         echo ::group::maacheck
-        grep -v "ERROR: too many states" packages/lib/$PACKAGE/libs/$PACKAGE.so.maacheck > packages/lib/$PACKAGE/libs/$PACKAGE.so.maacheck.filter || true
-        cat packages/lib/$PACKAGE/libs/$PACKAGE.so.maacheck.filter
-        if [ $(cat packages/lib/$PACKAGE/libs/$PACKAGE.so.maacheck.filter | wc -l) -gt 3 ]; then
+        cat packages/lib/$PACKAGE/libs/$PACKAGE.so.maacheck
+        if [ $(cat packages/lib/$PACKAGE/libs/$PACKAGE.so.maacheck | wc -l) -gt 3 ]; then
           FAIL=1
+          echo "maacheck failed."
         fi
         echo ::endgroup::
         echo ::group::bcheck
-        cat packages/lib/$PACKAGE/libs/$PACKAGE.so.bcheck
-        if [ $(cat packages/lib/$PACKAGE/libs/$PACKAGE.so.bcheck | wc -l) -gt 3 ]; then
+        grep -v "ERROR: too many states" packages/lib/$PACKAGE/libs/$PACKAGE.so.bcheck > packages/lib/$PACKAGE/libs/$PACKAGE.so.bcheck.filter || true
+        cat packages/lib/$PACKAGE/libs/$PACKAGE.so.bcheck.filter
+        if [ $(cat packages/lib/$PACKAGE/libs/$PACKAGE.so.bcheck.filter | wc -l) -gt 3 ]; then
           FAIL=1
+          echo "bcheck failed."
         fi
         echo ::endgroup::
         echo ::group::fficheck
         cat packages/lib/$PACKAGE/libs/$PACKAGE.so.fficheck
         if grep -q ERROR packages/lib/$PACKAGE/libs/$PACKAGE.so.fficheck; then
           FAIL=1
+          echo "fficheck failed."
         fi
         echo ::endgroup::
         if [ "$FAIL" = 1 ]; then
